version: '2'
services:
    web:
        build: .
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
            - mysql
    redis:
        image: redis
    mysql:
        build: ./mysql/
        restart: always
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"